<?php

if (!defined("PHORUM")) return;

require_once("./mods/markdown/Parsedown.php");

function phorum_mod_markdown_format($data)
{
    $parsedown = new Parsedown();
    // We don't use SafeMode here because Phorum already escaped the body 
    // using htmlspecialchars before this hook is called. 
    // This allows HTML generated by previous hooks (like BBCode) to pass through.
    $parsedown->setSafeMode(false);
    
    // Enable single line breaks as <br> tags (standard for forum posts)
    $parsedown->setBreaksEnabled(true);

    foreach ($data as $message_id => $message)
    {
        if (!isset($message['body'])) continue;

        // Skip if Markdown is explicitly disabled in meta
        if (!empty($message['meta']['disable_markdown'])) continue;

        $body = $message['body'];

        // Protect math blocks from Parsedown
        $math_blocks = array();
        
        // 1. Extract block math $$...$$
        $body = preg_replace_callback(
            '/(?<!\\\\)\$\$(.+?)\$\$/s',
            function($matches) use (&$math_blocks) {
                $idx = count($math_blocks);
                $math_blocks['%%MATH_BLOCK_' . $idx . '%%'] = '$$' . $matches[1] . '$$';
                return '%%MATH_BLOCK_' . $idx . '%%';
            },
            $body
        );

        // 2. Extract inline math $...$
        $body = preg_replace_callback(
            '/(?<!\\\\)\$([^\$\n]+?)\$/',
            function($matches) use (&$math_blocks) {
                $idx = count($math_blocks);
                $math_blocks['%%MATH_INLINE_' . $idx . '%%'] = '$' . $matches[1] . '$';
                return '%%MATH_INLINE_' . $idx . '%%';
            },
            $body
        );

        // Phorum adds '<phorum break>' before newlines in phorum_format_messages.
        // We remove them to let Markdown handle the layout correctly.
        $body = str_replace('<phorum break>', '', $body);

        // Replace HTML block-level alignment tags (center, div) with inline-level spans (with display: block)
        // to prevent Parsedown from disabling Markdown parsing inside them.
        $body = preg_replace('/<center( class="[^"]+")?>(.*?)<\/center>/is', '<span style="display: block; text-align: center;">$2</span>', $body);
        $body = preg_replace('/<div style="text-align:\s*(left|right|justify);" class="bbcode">(.*?)<\/div>/is', '<span style="display: block; text-align: $1;" class="bbcode">$2</span>', $body);

        // Insert a blank line before any long separator line of dashes (20+ dashes)
        // to prevent Parsedown from interpreting the preceding line of text as a header (H2).
        $body = preg_replace('/([^\n]+)\n(-{20,})\s*(\n|$)/', "$1\n\n$2\n", $body);

        // Phorum may have auto-linked URLs inside Markdown links.
        // For example: [text](<a href="http://...">http://...</a>)
        // Or: [text](<a rel="nofollow" target="_blank" href="http://...">http://...</a>)
        // We need to revert this so Parsedown can parse the Markdown link correctly.
        $body = preg_replace('/\]\(\s*\[?<a\s+[^>]*?href="([^"]+)".*?<\/a>\]?\s*\)/i', ']($1)', $body);

        // --- Video embedding start ---
        // 1. Clean up any auto-linked HTML tags inside [video] tags
        $body = preg_replace_callback(
            '/\[video\](.*?)\[\/video\]/is',
            function ($m) {
                return '[video]' . trim(strip_tags($m[1])) . '[/video]';
            },
            $body
        );

        // 2. YouTube [video] tag -> iframe
        $body = preg_replace_callback(
            '!\[video\](?:https?://)?(?:www\.)?(?:youtube\.com/(?:watch\?v=|embed/|v/|shorts/)|youtu\.be/)([\w_-]+).*?\[/video\]!is',
            function ($m) {
                return '<div class="video-container"><iframe src="https://www.youtube.com/embed/' . htmlspecialchars($m[1], ENT_QUOTES, 'UTF-8') . '" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>';
            },
            $body
        );

        // 3. Vimeo [video] tag -> iframe
        $body = preg_replace_callback(
            '!\[video\](?:https?://)?(?:www\.)?vimeo\.com/(\d+).*?\[/video\]!is',
            function ($m) {
                return '<div class="video-container"><iframe src="https://player.vimeo.com/video/' . htmlspecialchars($m[1], ENT_QUOTES, 'UTF-8') . '" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>';
            },
            $body
        );

        // 4. Auto-linked YouTube URLs -> iframe
        $body = preg_replace_callback(
            '/\[?<a\s+[^>]*?href="((?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:watch\?v=|embed\/|v\/|shorts\/)|youtu\.be\/)([\w_-]+)[a-z0-9;\/\?:@=\&\$\-_\.\+!*\'\(\),~%#]*)"[^>]*>.*?<\/a>\]?/is',
            function ($m) {
                return '<div class="video-container"><iframe src="https://www.youtube.com/embed/' . htmlspecialchars($m[2], ENT_QUOTES, 'UTF-8') . '" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>';
            },
            $body
        );

        // 5. Auto-linked Vimeo URLs -> iframe
        $body = preg_replace_callback(
            '/\[?<a\s+[^>]*?href="((?:https?:\/\/)?(?:www\.)?vimeo\.com\/(\d+)[a-z0-9;\/\?:@=\&\$\-_\.\+!*\'\(\),~%#]*)"[^>]*>.*?<\/a>\]?/is',
            function ($m) {
                return '<div class="video-container"><iframe src="https://player.vimeo.com/video/' . htmlspecialchars($m[2], ENT_QUOTES, 'UTF-8') . '" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>';
            },
            $body
        );

        // 6. Plain YouTube URLs not linked yet -> iframe
        $body = preg_replace_callback(
            '/(?<=^|\s)(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:watch\?v=|embed\/|v\/|shorts\/)|youtu\.be\/)([\w_-]+)[a-z0-9;\/\?:@=\&\$\-_\.\+!*\'\(\),~%#]*(?=\s|$)/is',
            function ($m) {
                return '<div class="video-container"><iframe src="https://www.youtube.com/embed/' . htmlspecialchars($m[1], ENT_QUOTES, 'UTF-8') . '" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>';
            },
            $body
        );

        // 7. Plain Vimeo URLs not linked yet -> iframe
        $body = preg_replace_callback(
            '/(?<=^|\s)(?:https?:\/\/)?(?:www\.)?vimeo\.com\/(\d+)[a-z0-9;\/\?:@=\&\$\-_\.\+!*\'\(\),~%#]*(?=\s|$)/is',
            function ($m) {
                return '<div class="video-container"><iframe src="https://player.vimeo.com/video/' . htmlspecialchars($m[1], ENT_QUOTES, 'UTF-8') . '" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>';
            },
            $body
        );
        // --- Video embedding end ---

        $body_parsed = $parsedown->text($body);

        // Restore protected math blocks
        if (!empty($math_blocks)) {
            $body_parsed = strtr($body_parsed, $math_blocks);
        }

        $data[$message_id]['body'] = $body_parsed;
    }

    return $data;
}

// Register the additional JavaScript code for this module to override BBCode editor actions.
function phorum_mod_markdown_javascript_register($data)
{
    $data[] = array(
        "module" => "markdown",
        "source" => "file(mods/markdown/markdown_editor_tools.js)"
    );

    return $data;
}

function phorum_mod_markdown_editor_tool_plugin()
{
    global $PHORUM;

    editor_tools_register_tool(
        'markdown_video',                  // Tool id
        'Vidéo',                           // Tool description
        './mods/markdown/video_icon.gif',  // Tool button icon
        'markdown_video_editor_tool()'     // Javascript action on button click
    );
}

// Quote hook, to override the default quoting format with clean Markdown quotes.
function phorum_mod_markdown_quote($data)
{
    if (!is_array($data)) return $data;
    $author = $data[0];
    $body = $data[1];

    if (function_exists('phorum_strip_body')) {
        $body = phorum_strip_body($body, false);
    }

    $body = trim($body);
    $body = str_replace("\n", "\n> ", $body);

    $quote_title = $author . " " . $GLOBALS["PHORUM"]["DATA"]["LANG"]["Wrote"] . ":";

    return "> **" . $quote_title . "**\n> " . $body . "\n\n";
}

?>
