<?php

if (!defined("PHORUM")) return;

require_once("./mods/markdown/Parsedown.php");

function phorum_mod_markdown_format($data)
{
    $parsedown = new Parsedown();
    // We don't use SafeMode here because Phorum already escaped the body 
    // using htmlspecialchars before this hook is called. 
    // This allows HTML generated by previous hooks (like BBCode) to pass through.
    $parsedown->setSafeMode(false);
    
    // Enable single line breaks as <br> tags (standard for forum posts)
    $parsedown->setBreaksEnabled(true);

    foreach ($data as $message_id => $message)
    {
        if (!isset($message['body'])) continue;

        // Skip if Markdown is explicitly disabled in meta
        if (!empty($message['meta']['disable_markdown'])) continue;

        $body = $message['body'];

        // Phorum adds '<phorum break>' before newlines in phorum_format_messages.
        // We remove them to let Markdown handle the layout correctly.
        $body = str_replace('<phorum break>', '', $body);

        $data[$message_id]['body'] = $parsedown->text($body);
    }

    return $data;
}

// Register the additional JavaScript code for this module to override BBCode editor actions.
function phorum_mod_markdown_javascript_register($data)
{
    $data[] = array(
        "module" => "markdown",
        "source" => "file(mods/markdown/markdown_editor_tools.js)"
    );

    return $data;
}

?>
